### PR TITLE
cppcheck and gcc compilation fixes

### PR DESCRIPTION
**Pull request by efernandez**

### CODE REVIEW

**Comment by efernandez** [comment]
I don't know why this pkg is no longer available as a debian.
Maybe there's a reason I don't see.
Could we try to push for that?

**Comment by mikepurvis** [comment]
@po1 Is there an upstream for this? We forked it from the old kforge and I believe are actively using it internally.

We'd be happy to create releases for Hydro and Indigo, but perhaps it would be better to move it to the ros-perception or ros-planning first.

@y22ma, @tfoote, thoughts on this?

**Comment by po1** [comment]
@mikepurvis maybe not. Reading my comment I now wonder why I said that. I was probably mistakenly thinking that this was an internal fork of ours...

Right now it doesn't seem to be vital, as nobody seems to have complained that it wasn't available in hydro. We used to use it at PAL, and would be happy if it were released, but I don't know if there is a strong motivation to move it to one of the ros- groups.

I guess you could release it under https://github.com/clearpath-gbp for the time being. If you need any help, I'd be happy to give a hand.

**Comment by mikepurvis** [comment]
Happy to release via clearpath-gbp, but will hold for commentary from others on whether to wait and first move the repo.

**Pull request merged**
